//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Emk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TRIM(surname), TRIM(firstname), TRIM(middlename), pers_code, tax_file_no, member_id, sex FROM staff WHERE is_active= &apos;Y&apos; and member_type = 1.
        /// </summary>
        internal static string GetDoctors_Scropt {
            get {
                return ResourceManager.GetString("GetDoctors_Scropt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IsLicenseValid {
            get {
                return ResourceManager.GetString("IsLicenseValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH p_value AS (
        ///    SELECT *
        ///    FROM (
        ///        SELECT Param_Code, param_value
        ///        FROM APOC_Parameters_Values apv JOIN APOC_Parameters ap 
        ///        WHERE Param_Code IN (&apos;ACTIVATE_N3H&apos;,&apos;N3H_EMK_URL&apos;,&apos;N3H_PAT_URL&apos;,&apos;N3H_DATA_ON&apos;,&apos;N3H_REFR_TIME&apos;,&apos;N3H_TR_MODE&apos;,&apos;N3H_BY_DAYS&apos;,&apos;N3H_PER_FROM&apos;,&apos;N3H_PER_TO&apos;)
        ///    ) up
        ///    PIVOT 
        ///    ( MIN([param_value]) 
        ///     for Param_Code in (&apos;ACTIVATE_N3H&apos;,&apos;N3H_EMK_URL&apos;,&apos;N3H_PAT_URL&apos;,&apos;N3H_DATA_ON&apos;,&apos;N3H_REFR_TIME&apos;,&apos;N3H_TR_MODE&apos;,&apos;N3H_BY_DAYS&apos;,&apos;N3H_PER_FROM&apos;,&apos;N3H_PER_TO&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sql_Parameters {
            get {
                return ResourceManager.GetString("Sql_Parameters", resourceCulture);
            }
        }
    }
}
